services:
  proxy:
    build: ./proxy/
    container_name: proxy
    networks:
      - rent_gen_android
    volumes:
      - $PWD/certificates:/root/.mitmproxy
      - $PWD/log:/log
  android:
    build: ./android/
    container_name: android
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/kvm
    networks:
      - rent_gen_android
    volumes:
      - $PWD/android/conf:/conf
      - $PWD/certificates/mitmproxy-ca-cert.cer:/ca-cert.cer
      - $PWD/android/code:/code
  http_server:
    build: ./http_server/
    container_name: http_server
    networks:
      - rent_gen_android
    volumes:
      - $PWD/http_server/code:/code
      - $PWD/log:/log
    ports:
      - 8080:8080

networks:
  rent_gen_android:
    driver: bridge