services:
  proxy:
    build: ./proxy/
    container_name: proxy
    networks:
      - rent_gen_android
    volumes:
      - $PWD/certificates:/root/.mitmproxy
  android:
    build: ./android/
    container_name: android
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/kvm
    networks:
      - rent_gen_android
    volumes:
      - $PWD/android/conf:/conf
      - $PWD/certificates/mitmproxy-ca-cert.cer:/ca-cert.cer

networks:
  rent_gen_android:
    driver: bridge